from fpdf import FPDF
import datetime
import os

class MedicalReport(FPDF):
    def header(self):
        self.set_fill_color(30, 41, 59)
        self.rect(0, 0, 210, 30, 'F')
        
        self.set_font('Arial', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 8)
        self.cell(0, 10, 'ENCEPHLO DIAGNOSTICS', 0, 0, 'L')
        
        self.set_font('Arial', '', 10)
        self.set_xy(10, 18)
        self.cell(0, 10, 'Neural Analysis & Triage System', 0, 0, 'L')
        
        current_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        self.set_xy(150, 10)
        self.set_font('Arial', 'B', 10)
        self.cell(50, 10, f'DATE: {current_date}', 0, 0, 'R')
        self.ln(25)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, 'CONFIDENTIAL MEDICAL RECORD', 0, 1, 'C')
        self.cell(0, 5, 'Generated by AI Assistant. Consult a radiologist for final diagnosis.', 0, 0, 'C')

def create_pdf(prediction, confidence, original_path, heatmap_path=None):
    pdf = MedicalReport()
    pdf.add_page()
    
    pdf.set_y(40)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, "EXAMINATION DETAILS", 0, 1)
    
    pdf.set_fill_color(245, 247, 250)
    pdf.rect(10, 50, 190, 25, 'F')
    
    pdf.set_font('Arial', '', 10)
    pdf.set_xy(15, 55)
    pdf.cell(40, 6, "Patient ID:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(50, 6, "ANON-7492-X", 0, 1)
    
    pdf.set_xy(15, 62)
    pdf.set_font('Arial', '', 10)
    pdf.cell(40, 6, "Scan Modality:", 0, 0)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(50, 6, "MRI (T1-Weighted)", 0, 1)

    pdf.set_xy(10, 90)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, "AI INTERPRETATION", 0, 1)

    if prediction == "No Tumor":
        pdf.set_fill_color(220, 252, 231)
        text_color = (22, 101, 52)
        status_text = "NEGATIVE FOR TUMOR"
    else:
        pdf.set_fill_color(254, 226, 226)
        text_color = (153, 27, 27)
        status_text = f"POSITIVE MATCH: {prediction.upper()}"

    pdf.rect(10, 100, 190, 15, 'F')
    
    pdf.set_xy(15, 100)
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(*text_color)
    pdf.cell(100, 15, status_text, 0, 0, 'L')
    
    pdf.set_xy(150, 100)
    pdf.cell(40, 15, f"Confidence: {confidence:.1f}%", 0, 0, 'R')

    pdf.set_xy(10, 130)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, "RADIOLOGICAL IMAGING", 0, 1)
    
    y_pos = 140
    
    if os.path.exists(original_path):
        pdf.image(original_path, x=15, y=y_pos, w=85, h=85)
        pdf.rect(15, y_pos, 85, 85)
        pdf.set_xy(15, y_pos + 87)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(85, 5, "Processed Input", 0, 0, 'C')

    if heatmap_path and os.path.exists(heatmap_path):
        pdf.image(heatmap_path, x=110, y=y_pos, w=85, h=85)
        pdf.rect(110, y_pos, 85, 85)
        pdf.set_xy(110, y_pos + 87)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(85, 5, "Grad-CAM Attention", 0, 0, 'C')

    return pdf.output(dest='S').encode('latin1')
